language: ruby
rvm: 2.0.0
script: bin/rake spec
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
  - psql -c "CREATE USER ivan WITH PASSWORD '';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: DTaWj09c/bbSAx+eKgnfeKHfKQayhf97Mt9RE6zYtw+x35w9NFX52MtSc+d+bu4w+JUesxGSLL2hNzP5SEiZ2Bp9oviZA8yMJ6+vQf9cqNUjIS1yqOhJSaAGjCx7ySxvN+JshizUaUhTh2GI446I/LaykrgghCBKxQ7D0Kdv820=
  app: pure-shelf-9474
  on:
    repo: i5okie/ticketee
